// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCompany = "companies"

// Company mapped from table <companies>
type Company struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyName string    `gorm:"column:company_name;not null" json:"company_name"`
	Address     string    `gorm:"column:address" json:"address"`
	City        string    `gorm:"column:city" json:"city"`
	Province    string    `gorm:"column:province" json:"province"`
	Country     string    `gorm:"column:country" json:"country"`
	Phone1      string    `gorm:"column:phone1;not null" json:"phone1"`
	Phone2      string    `gorm:"column:phone2" json:"phone2"`
	Email1      string    `gorm:"column:email1;not null" json:"email1"`
	Email2      string    `gorm:"column:email2" json:"email2"`
	Sales       float64   `gorm:"column:sales" json:"sales"`
	DateAdded   time.Time `gorm:"column:date_added" json:"date_added"`
	UserAddedID int32     `gorm:"column:user_added_id" json:"user_added_id"`
}

// TableName Company's table name
func (*Company) TableName() string {
	return TableNameCompany
}
