// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompanyEmployee = "company_employees"

// CompanyEmployee mapped from table <company_employees>
type CompanyEmployee struct {
	ID         int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID int32 `gorm:"column:employee_id;not null" json:"employee_id"`
	CompanyID  int32 `gorm:"column:company_id;not null" json:"company_id"`
}

// TableName CompanyEmployee's table name
func (*CompanyEmployee) TableName() string {
	return TableNameCompanyEmployee
}
