// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameListCompany = "list_companies"

// ListCompany mapped from table <list_companies>
type ListCompany struct {
	ID        int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyID int32 `gorm:"column:company_id;not null" json:"company_id"`
	ListID    int32 `gorm:"column:list_id;not null" json:"list_id"`
}

// TableName ListCompany's table name
func (*ListCompany) TableName() string {
	return TableNameListCompany
}
